/*
 * Auto-generated by Frida. Please modify to match the signature of -[INDeferredLocalizedString initWithDeferredFormat:fromTable:bundleIdentifier:bundleURL:arguments:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[INDeferredLocalizedString initWithDeferredFormat:${args[2]} fromTable:${args[3]} bundleIdentifier:${args[4]} bundleURL:${args[5]} arguments:${args[6]}]`);
  },

  onLeave(log, retval, state) {
  }
});
