/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSData _AESCBC128PKCS5PKCS7PaddingOperation:key:iv:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSData _AESCBC128PKCS5PKCS7PaddingOperation:${args[2]} key:${args[3]} iv:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
