/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSData _base64EncodingAsString:withOptions:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSData _base64EncodingAsString:${args[2]} withOptions:${args[3]}]`);
  },

  onLeave(log, retval, state) {
  }
});
