/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSData _decodeBase64EncodedCharacterBuffer:length:options:buffer:bufferLength:state:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSData _decodeBase64EncodedCharacterBuffer:${args[2]} length:${args[3]} options:${args[4]} buffer:${args[5]} bufferLength:${args[6]} state:${args[7]}]`);
  },

  onLeave(log, retval, state) {
  }
});
