/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSData _faCreateContextWithImage:crop:diameter:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSData _faCreateContextWithImage:${args[2]} crop:${args[3]} diameter:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
