/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSData _faCircularImageDataWithDiameter:cropRect:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSData _faCircularImageDataWithDiameter:${args[2]} cropRect:${args[3]}]`);
  },

  onLeave(log, retval, state) {
  }
});
