/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSData _ICSStringWithOptions:appendingToString:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSData _ICSStringWithOptions:${args[2]} appendingToString:${args[3]}]`);
  },

  onLeave(log, retval, state) {
  }
});
