/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSData _in_writeDataToPathForImage:storeType:error:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSData _in_writeDataToPathForImage:${args[2]} storeType:${args[3]} error:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
