/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSData _ISMutableStoreIndex_addValue:size:forUUID:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSData _ISMutableStoreIndex_addValue:${args[2]} size:${args[3]} forUUID:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
