/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSData abu_eb_dataByGZipCompressingAtLevel:windowSize:memoryLevel:strategy:error:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSData abu_eb_dataByGZipCompressingAtLevel:${args[2]} windowSize:${args[3]} memoryLevel:${args[4]} strategy:${args[5]} error:${args[6]}]`);
  },

  onLeave(log, retval, state) {
  }
});
