/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSData AESCBC256EncryptWithKey:gIv:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSData AESCBC256EncryptWithKey:${args[2]} gIv:${args[3]}]`);
  },

  onLeave(log, retval, state) {
  }
});
