/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSData af_enumerateDigestibleChunksWithOptions:usingBlock:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSData af_enumerateDigestibleChunksWithOptions:${args[2]} usingBlock:${args[3]}]`);
  },

  onLeave(log, retval, state) {
  }
});
