/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSData ams_decryptUsingDataProtectionClass:initializationVectorData:tagData:error:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSData ams_decryptUsingDataProtectionClass:${args[2]} initializationVectorData:${args[3]} tagData:${args[4]} error:${args[5]}]`);
  },

  onLeave(log, retval, state) {
  }
});
