/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSData AT_aes256_encrypt:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSData AT_aes256_encrypt:${args[2]}]`);
  },

  onLeave(log, retval, state) {
  }
});
