/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSData CKDescriptionPropertiesWithPublic:private:shouldExpand:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSData CKDescriptionPropertiesWithPublic:${args[2]} private:${args[3]} shouldExpand:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
