/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSData getFileIDFromXattr:docID:genCount:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSData getFileIDFromXattr:${args[2]} docID:${args[3]} genCount:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
