/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSData HMDBUAES128DecryptedDataWithKey:iv:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSData HMDBUAES128DecryptedDataWithKey:${args[2]} iv:${args[3]}]`);
  },

  onLeave(log, retval, state) {
  }
});
