/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSData ic_encryptedDataWithKey:tag:initialVector:error:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSData ic_encryptedDataWithKey:${args[2]} tag:${args[3]} initialVector:${args[4]} error:${args[5]}]`);
  },

  onLeave(log, retval, state) {
  }
});
