/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSData initWithBytes:length:copy:freeWhenDone:bytesAreVM:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSData initWithBytes:${args[2]} length:${args[3]} copy:${args[4]} freeWhenDone:${args[5]} bytesAreVM:${args[6]}]`);
  },

  onLeave(log, retval, state) {
  }
});
