/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSData initWithContentsOfURL:options:maxLength:error:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSData initWithContentsOfURL:${args[2]} options:${args[3]} maxLength:${args[4]} error:${args[5]}]`);
  },

  onLeave(log, retval, state) {
  }
});
