/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSData MI_writeAtomicallyToURL:withMode:owner:group:protectionClass:error:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSData MI_writeAtomicallyToURL:${args[2]} withMode:${args[3]} owner:${args[4]} group:${args[5]} protectionClass:${args[6]} error:${args[7]}]`);
  },

  onLeave(log, retval, state) {
  }
});
