/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSData veaes_decryptWithKeyData:size:ivData:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSData veaes_decryptWithKeyData:${args[2]} size:${args[3]} ivData:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
