/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSData WindCryptPCBCWithOp:algorithm:key:iv:error:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSData WindCryptPCBCWithOp:${args[2]} algorithm:${args[3]} key:${args[4]} iv:${args[5]} error:${args[6]}]`);
  },

  onLeave(log, retval, state) {
  }
});
