/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSData WindCryptWithOp:algorithm:optionMode:padding:key:iv:error:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSData WindCryptWithOp:${args[2]} algorithm:${args[3]} optionMode:${args[4]} padding:${args[5]} key:${args[6]} iv:${args[7]} error:${args[8]}]`);
  },

  onLeave(log, retval, state) {
  }
});
