/*
 * Auto-generated by Frida. Please modify to match the signature of +[NEHeimdallCrash crashWithReason:code:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[NEHeimdallCrash crashWithReason:${args[2]} code:${args[3]}]`);
  },

  onLeave(log, retval, state) {
  }
});
