/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSFileManager __im_getItemsRemovedFromiCloudBackupsAtDirectoryPath:outPaths:outRemovedPaths:error:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSFileManager __im_getItemsRemovedFromiCloudBackupsAtDirectoryPath:${args[2]} outPaths:${args[3]} outRemovedPaths:${args[4]} error:${args[5]}]`);
  },

  onLeave(log, retval, state) {
  }
});
