/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSFileManager _cn_getValue:forExtendendAttribute:url:error:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSFileManager _cn_getValue:${args[2]} forExtendendAttribute:${args[3]} url:${args[4]} error:${args[5]}]`);
  },

  onLeave(log, retval, state) {
  }
});
