/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSFileManager _IGDirectory:userPk:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSFileManager _IGDirectory:${args[2]} userPk:${args[3]}]`);
  },

  onLeave(log, retval, state) {
  }
});
