/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSFileManager _moveItemAtPath:toPath:uniquePath:error:asCopy:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSFileManager _moveItemAtPath:${args[2]} toPath:${args[3]} uniquePath:${args[4]} error:${args[5]} asCopy:${args[6]}]`);
  },

  onLeave(log, retval, state) {
  }
});
