/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSFileManager _srMoveFileFromURL:toURL:completion:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSFileManager _srMoveFileFromURL:${args[2]} toURL:${args[3]} completion:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
