/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSFileManager _web_fileExistsAtPath_nowarn:isDirectory:traverseLink:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSFileManager _web_fileExistsAtPath_nowarn:${args[2]} isDirectory:${args[3]} traverseLink:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
