/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSFileManager _web_createFileAtPathWithIntermediateDirectories:contents:attributes:directoryAttributes:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSFileManager _web_createFileAtPathWithIntermediateDirectories:${args[2]} contents:${args[3]} attributes:${args[4]} directoryAttributes:${args[5]}]`);
  },

  onLeave(log, retval, state) {
  }
});
