/*
 * Auto-generated by Frida. Please modify to match the signature of +[NSFileManager ane_addWriteModeIfMissing:originalMode:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[NSFileManager ane_addWriteModeIfMissing:${args[2]} originalMode:${args[3]}]`);
  },

  onLeave(log, retval, state) {
  }
});
