/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSFileManager archivePathToFile:toFile:createPKZipArchive:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSFileManager archivePathToFile:${args[2]} toFile:${args[3]} createPKZipArchive:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
