/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSFileManager createDirectoryAtPath:withIntermediateDirectories:attributes:error:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSFileManager createDirectoryAtPath:${args[2]} withIntermediateDirectories:${args[3]} attributes:${args[4]} error:${args[5]}]`);
  },

  onLeave(log, retval, state) {
  }
});
