/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSFileManager directoryContentsAtPath:matchingExtension:options:keepExtension:error:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSFileManager directoryContentsAtPath:${args[2]} matchingExtension:${args[3]} options:${args[4]} keepExtension:${args[5]} error:${args[6]}]`);
  },

  onLeave(log, retval, state) {
  }
});
