/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSFileManager entriesForContentsOfDirectoryAtURL:includingDates:block:error:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSFileManager entriesForContentsOfDirectoryAtURL:${args[2]} includingDates:${args[3]} block:${args[4]} error:${args[5]}]`);
  },

  onLeave(log, retval, state) {
  }
});
