/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSFileManager enumeratorAtURL:includingPropertiesForKeys:options:errorHandler:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSFileManager enumeratorAtURL:${args[2]} includingPropertiesForKeys:${args[3]} options:${args[4]} errorHandler:${args[5]}]`);
  },

  onLeave(log, retval, state) {
  }
});
