/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSFileManager evictUbiquitousItemAtURL:error:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSFileManager evictUbiquitousItemAtURL:${args[2]} error:${args[3]}]`);
  },

  onLeave(log, retval, state) {
  }
});
