/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSFileManager fileAttributesAtPath:traverseLink:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSFileManager fileAttributesAtPath:${args[2]} traverseLink:${args[3]}]`);
  },

  onLeave(log, retval, state) {
  }
});
