/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSFileManager filesystemItemMoveOperation:shouldMoveItemAtPath:toPath:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSFileManager filesystemItemMoveOperation:${args[2]} shouldMoveItemAtPath:${args[3]} toPath:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
