/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSFileManager filesystemItemCopyOperation:shouldProceedAfterError:copyingItemAtPath:toPath:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSFileManager filesystemItemCopyOperation:${args[2]} shouldProceedAfterError:${args[3]} copyingItemAtPath:${args[4]} toPath:${args[5]}]`);
  },

  onLeave(log, retval, state) {
  }
});
