/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSFileManager filesystemItemLinkOperation:shouldLinkItemAtPath:toPath:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSFileManager filesystemItemLinkOperation:${args[2]} shouldLinkItemAtPath:${args[3]} toPath:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
