/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSFileManager getFileSystemRepresentation:maxLength:withPath:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSFileManager getFileSystemRepresentation:${args[2]} maxLength:${args[3]} withPath:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
