/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSFileManager getRelationship:ofDirectoryAtURL:toItemAtURL:error:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSFileManager getRelationship:${args[2]} ofDirectoryAtURL:${args[3]} toItemAtURL:${args[4]} error:${args[5]}]`);
  },

  onLeave(log, retval, state) {
  }
});
