/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSFileManager getRelationship:ofDirectory:inDomain:toItemAtURL:error:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSFileManager getRelationship:${args[2]} ofDirectory:${args[3]} inDomain:${args[4]} toItemAtURL:${args[5]} error:${args[6]}]`);
  },

  onLeave(log, retval, state) {
  }
});
