/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSFileManager if_auditTokenForExtendedAttributeNamed:ofItemAtURL:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSFileManager if_auditTokenForExtendedAttributeNamed:${args[2]} ofItemAtURL:${args[3]}]`);
  },

  onLeave(log, retval, state) {
  }
});
