/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSFileManager if_setAuditToken:forExtendedAttributeNamed:ofItemAtURL:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSFileManager if_setAuditToken:${args[2]} forExtendedAttributeNamed:${args[3]} ofItemAtURL:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
