/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSFileManager moveItemAtURL:toURL:error:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSFileManager moveItemAtURL:${args[2]} toURL:${args[3]} error:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
