/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSFileManager replaceItemAtURL:withItemAtURL:backupItemName:options:resultingItemURL:error:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSFileManager replaceItemAtURL:${args[2]} withItemAtURL:${args[3]} backupItemName:${args[4]} options:${args[5]} resultingItemURL:${args[6]} error:${args[7]}]`);
  },

  onLeave(log, retval, state) {
  }
});
