/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSFileManager setExtendedAttribute:forKey:atPath:error:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSFileManager setExtendedAttribute:${args[2]} forKey:${args[3]} atPath:${args[4]} error:${args[5]}]`);
  },

  onLeave(log, retval, state) {
  }
});
