/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSFileManager setUbiquitous:itemAtURL:destinationURL:error:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSFileManager setUbiquitous:${args[2]} itemAtURL:${args[3]} destinationURL:${args[4]} error:${args[5]}]`);
  },

  onLeave(log, retval, state) {
  }
});
