/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSFileManager synchronouslyGetFileProviderServiceWithName:forItemAtURL:completionHandler:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSFileManager synchronouslyGetFileProviderServiceWithName:${args[2]} forItemAtURL:${args[3]} completionHandler:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
