/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSFileManager URLForDirectory:inDomain:appropriateForURL:create:error:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSFileManager URLForDirectory:${args[2]} inDomain:${args[3]} appropriateForURL:${args[4]} create:${args[5]} error:${args[6]}]`);
  },

  onLeave(log, retval, state) {
  }
});
