/*
 * Auto-generated by Frida. Please modify to match the signature of +[BMKCrashFileUtils bmk_writeCrashDataToFile:crashFileName:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[BMKCrashFileUtils bmk_writeCrashDataToFile:${args[2]} crashFileName:${args[3]}]`);
  },

  onLeave(log, retval, state) {
  }
});
