/*
 * Auto-generated by Frida. Please modify to match the signature of -[DoorDuDataService _getPramaSignFromParam:timestamp:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {

    var str = ObjC.classes.NSString;
    var newValue = str.stringWithFormat_("text");
    args[2] = newValue;
    log(`-[DoorDuDataService _getPramaSignFromParam:${args[2]} timestamp:${args[3]}]`);
    log('--2--' + ObjC.Object(args[2]) + '--2--');
    //log('Sign输入dump：---' + hexdump(args[2]) + '---');
    log('--3--' + ObjC.Object(args[3]) + '--3--');


  },

  onLeave(log, retval, state) {
  }
});
