/*
 * Auto-generated by Frida. Please modify to match the signature of -[YYLabel _getHighlightAtPoint:range:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[YYLabel _getHighlightAtPoint:${args[2]} range:${args[3]}]`);
  },

  onLeave(log, retval, state) {
  }
});
