/*
 * Auto-generated by Frida. Please modify to match the signature of -[__NSCFString getLineStart:end:contentsEnd:forRange:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[__NSCFString getLineStart:${args[2]} end:${args[3]} contentsEnd:${args[4]} forRange:${args[5]}]`);
  },

  onLeave(log, retval, state) {
  }
});
