/*
 * Auto-generated by Frida. Please modify to match the signature of -[UITabBarButtonLabel _UIAppearance_setTitleTextAttributes:forState:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[UITabBarButtonLabel _UIAppearance_setTitleTextAttributes:${args[2]} forState:${args[3]}]`);
  },

  onLeave(log, retval, state) {
  }
});
