/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSSimpleCString _newSubstringWithRange:zone:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSSimpleCString _newSubstringWithRange:${args[2]} zone:${args[3]}]`);
  },

  onLeave(log, retval, state) {
  }
});
