/*
 * Auto-generated by Frida. Please modify to match the signature of -[__NSLocalizedString initWithString:withFormatConfiguration:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[__NSLocalizedString initWithString:${args[2]} withFormatConfiguration:${args[3]}]`);
  },

  onLeave(log, retval, state) {
  }
});
