/*
 * Auto-generated by Frida. Please modify to match the signature of +[DoorDuDataManager openDoorWithRoomId:doorId:tid:openType:doorOrderId:content:completion:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[DoorDuDataManager openDoorWithRoomId:${ObjC.Object(args[2])} doorId:${ObjC.Object(args[3])} tid:${args[4]} openType:${ObjC.Object(args[5])} doorOrderId:${ObjC.Object(args[6])} content:${ObjC.Object(args[7])} completion:${args[8]}]`);
    // log(`-[DoorDuDataService POST:${ObjC.Object(args[2])} parameters:${ObjC.Object(args[3])} success:${args[4]} failure:${args[5]}]`);
  },

  onLeave(log, retval, state) {
  }
});
