/*
 * Auto-generated by Frida. Please modify to match the signature of +[BeiZiGTMBase64 baseDecode:srcLen:destBytes:destLen:charset:requirePadding:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[BeiZiGTMBase64 baseDecode:${args[2]} srcLen:${args[3]} destBytes:${args[4]} destLen:${args[5]} charset:${args[6]} requirePadding:${args[7]}]`);
  },

  onLeave(log, retval, state) {
  }
});
