/*
 * Auto-generated by Frida. Please modify to match the signature of +[BeiZiGTMBase64 baseEncode:length:charset:padded:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[BeiZiGTMBase64 baseEncode:${args[2]} length:${args[3]} charset:${args[4]} padded:${args[5]}]`);
  },

  onLeave(log, retval, state) {
  }
});
