/*
 * Auto-generated by Frida. Please modify to match the signature of +[UIAlertController alertControllerWithTitle:message:preferredStyle:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('Methods :' + Thread.backtrace(this.context,Backtracer.ACCURATE).map(DebugSymbol.fromAddress).join('\n') + '\n');
    log(`+[UIAlertController alertControllerWithTitle:${args[2]} message:${args[3]} preferredStyle:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
