/*
 * Auto-generated by Frida. Please modify to match the signature of -[__NSCFLocalizedAttributedString initWithAttributedStringMarkdown:formatConfiguration:tableURL:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[__NSCFLocalizedAttributedString initWithAttributedStringMarkdown:${args[2]} formatConfiguration:${args[3]} tableURL:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
