/*
 * Auto-generated by Frida. Please modify to match the signature of -[JKHttpApplyReqManager beginWithApplyHttpServer:httpMethod:path:requestData:progress:resultBlock:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[JKHttpApplyReqManager beginWithApplyHttpServer:${ObjC.Object(args[2])} httpMethod:${args[3]} path:${args[4]} requestData:${ObjC.Object(args[5])} progress:${args[6]} resultBlock:${args[7]}]`);
  },

  onLeave(log, retval, state) {
    log("JKHttpApplyReqManager retval: " + ObjC.Object(retval));
  }
});
