/*
 * Auto-generated by Frida. Please modify to match the signature of -[PLIndicatorFileCoordinator _setActivityIndicatorWithPath:flag:crashRecovery:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[PLIndicatorFileCoordinator _setActivityIndicatorWithPath:${args[2]} flag:${args[3]} crashRecovery:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
