/*
 * Auto-generated by Frida. Please modify to match the signature of -[PLIndicatorFileCoordinator setImageWriter:isBusy:crashRecoverySupport:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[PLIndicatorFileCoordinator setImageWriter:${args[2]} isBusy:${args[3]} crashRecoverySupport:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
