/*
 * Auto-generated by Frida. Please modify to match the signature of -[HTTPFacade doHttpRequestWithParams:uri:completeBlock:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('Methods :' + Thread.backtrace(this.context,Backtracer.ACCURATE).map(DebugSymbol.fromAddress).join('\n') + '\n');
    log(`-[HTTPFacade doHttpRequestWithParams:${ObjC.Object(args[2])} uri:${ObjC.Object(args[3])} completeBlock:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});


//_t_=1742354788&adid=aac2beb7c36e4f0c67c24a3af7546016f93adb97&appId=homework&bundleID=com.baidu.homework&
// channel=appstore&cuid=90acb9ecd86b5722fdfe9b80bb4c15b8b3d9c3aa&dayivc=65&device=iPhone%207&did=03911987022000020a782f804000002c&feSkinName=skin-gray&hybrid=1&iOSVersion=15.8.3&isNotchScreen=0&nt=wifi&os=ios&password=d477887b0636e5d87f79cc25c99d7dc9&
// personalRecommendNA=1&phone=MwnqMwnNGwcguWh%3D&screenscale=2&screensize=1334x750&sign=8671b77ac640a6241a33c38eb14ef667&token=2_XPXQH3c5HRPtFHkSwi3sCCURmT25QfxM&vc=1320&vcname=14.19.0&yongsterStatus=0&zbkvc=960