/*
 * Auto-generated by Frida. Please modify to match the signature of -[PRPinyinString initWithUncheckedString:score:originalLength:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[PRPinyinString initWithUncheckedString:${args[2]} score:${args[3]} originalLength:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
