/*
 * Auto-generated by Frida. Please modify to match the signature of -[PRPinyinString initWithString:syllableCount:lastSyllableIsPartial:score:originalLength:originalCheckedLength:numberOfModifications:modificationTypes:originalModificationRanges:finalModificationRanges:originalSyllableRanges:originalAdditionalSyllableRanges:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[PRPinyinString initWithString:${args[2]} syllableCount:${args[3]} lastSyllableIsPartial:${args[4]} score:${args[5]} originalLength:${args[6]} originalCheckedLength:${args[7]} numberOfModifications:${args[8]} modificationTypes:${args[9]} originalModificationRanges:${args[10]} finalModificationRanges:${args[11]} originalSyllableRanges:${args[12]} originalAdditionalSyllableRanges:${args[13]}]`);
  },

  onLeave(log, retval, state) {
  }
});
