/*
 * Auto-generated by Frida. Please modify to match the signature of -[PRPinyinString initWithString:syllableCount:lastSyllableIsPartial:score:originalLength:modificationType:originalModificationRange:finalModificationRange:originalSyllableRange:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[PRPinyinString initWithString:${args[2]} syllableCount:${args[3]} lastSyllableIsPartial:${args[4]} score:${args[5]} originalLength:${args[6]} modificationType:${args[7]} originalModificationRange:${args[8]} finalModificationRange:${args[9]} originalSyllableRange:${args[10]}]`);
  },

  onLeave(log, retval, state) {
  }
});
