/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSMutableString _cfPad:length:padIndex:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSMutableString _cfPad:${args[2]} length:${args[3]} padIndex:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
