/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSMutableString _replaceOccurrencesOfRegularExpressionPattern:withTemplate:options:range:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSMutableString _replaceOccurrencesOfRegularExpressionPattern:${args[2]} withTemplate:${args[3]} options:${args[4]} range:${args[5]}]`);
  },

  onLeave(log, retval, state) {
  }
});
