/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSMutableString appendPrettyInt:withName:indent:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSMutableString appendPrettyInt:${args[2]} withName:${args[3]} indent:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
