/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSMutableString appendToStringAtColumnWithContent:column:content:appendAsNewLine:addNewLine:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSMutableString appendToStringAtColumnWithContent:${args[2]} column:${args[3]} content:${args[4]} appendAsNewLine:${args[5]} addNewLine:${args[6]}]`);
  },

  onLeave(log, retval, state) {
  }
});
