/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSMutableString applyRegex:withReplacementTemplate:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSMutableString applyRegex:${args[2]} withReplacementTemplate:${args[3]}]`);
  },

  onLeave(log, retval, state) {
  }
});
