/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSMutableString replaceCharactersInRange:withCString:length:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSMutableString replaceCharactersInRange:${args[2]} withCString:${args[3]} length:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
