/*
 * Auto-generated by Frida. Please modify to match the signature of +[QBGTMBase64 encodeBytes:length:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[QBGTMBase64 encodeBytes:${args[2]} length:${args[3]}]`);
  },

  onLeave(log, retval, state) {
  }
});
