/*
 * Auto-generated by Frida. Please modify to match the signature of -[BSUIRelativeDateLabel timerFiredWithValue:forResolution:comparedToNow:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[BSUIRelativeDateLabel timerFiredWithValue:${args[2]} forResolution:${args[3]} comparedToNow:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
