/*
 * Auto-generated by Frida. Please modify to match the signature of -[_UIActivityGroupActivityCellTitleLabel sizeThatFits:sizeCategory:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[_UIActivityGroupActivityCellTitleLabel sizeThatFits:${args[2]} sizeCategory:${args[3]}]`);
  },

  onLeave(log, retval, state) {
  }
});
