/*
 * Auto-generated by Frida. Please modify to match the signature of +[GTMBase64 stringByWebSafeEncodingData:padded:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[GTMBase64 stringByWebSafeEncodingData:${args[2]} padded:${args[3]}]`);
  },

  onLeave(log, retval, state) {
  }
});
