/*
 * Auto-generated by Frida. Please modify to match the signature of -[MFMutableData _flushToDisk:capacity:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[MFMutableData _flushToDisk:${args[2]} capacity:${args[3]}]`);
  },

  onLeave(log, retval, state) {
  }
});
