/*
 * Auto-generated by Frida. Please modify to match the signature of -[MFMutableData _initWithFd:path:mutable:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[MFMutableData _initWithFd:${args[2]} path:${args[3]} mutable:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
