/*
 * Auto-generated by Frida. Please modify to match the signature of -[MKTransitInfoLabelView _setFont:custom:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[MKTransitInfoLabelView _setFont:${args[2]} custom:${args[3]}]`);
  },

  onLeave(log, retval, state) {
  }
});
