/*
 * Auto-generated by Frida. Please modify to match the signature of -[MKTransitInfoLabelView initWithLabelItems:iconSize:shieldSize:spaceBetweenShields:maxWidth:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[MKTransitInfoLabelView initWithLabelItems:${args[2]} iconSize:${args[3]} shieldSize:${args[4]} spaceBetweenShields:${args[5]} maxWidth:${args[6]}]`);
  },

  onLeave(log, retval, state) {
  }
});
