/*
 * Auto-generated by Frida. Please modify to match the signature of -[OS_dispatch_data_empty _getContext].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[OS_dispatch_data_empty _getContext]`);
  },

  onLeave(log, retval, state) {
  }
});
