/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSFileSubarbitrationClaim forwardUsingConnection:withServer:crashHandler:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSFileSubarbitrationClaim forwardUsingConnection:${args[2]} withServer:${args[3]} crashHandler:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
