/*
 * Auto-generated by Frida. Please modify to match the signature of -[UNLocalizedString _initWithKey:arguments:value:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[UNLocalizedString _initWithKey:${args[2]} arguments:${args[3]} value:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
