/*
 * Auto-generated by Frida. Please modify to match the signature of CC_MD5.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('CC_MD5() onEnter: ---' + args[0].readCString(args[1].toInt32()) + '---');
    this.args2 = args[2];
  },

  onLeave(log, retval, state) {
    log('CC_MD5() onLeave: ' + hexdump(this.args2, {length: 16}));
  }
});

