/*
 * Auto-generated by Frida. Please modify to match the signature of CC_SHA224_Final.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`CC_SHA224_Final(md=${args[0]}, c=${args[1]})`);
  },

  onLeave(log, retval, state) {
  }
});
