/*
 * Auto-generated by Frida. Please modify to match the signature of CC_SHA1_Update.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`CC_SHA1_Update(c=${args[0]}, data=${args[1]}, len=${args[2]})`);
  },

  onLeave(log, retval, state) {
  }
});
