/*
 * Auto-generated by Frida. Please modify to match the signature of CCCrypt.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
var isEncrypted = args[0].toInt32();
this.isOn = false;
if (isEncrypted === 0){
  this.isOn = true;
  log('CCCrypt key = ' + args[3].readCString(args[4].toInt32()));
  log('CCCrypt dataIn = ' + args[6].readCString(args[7].toInt32()));
  log(`CCCrypt(op=${args[0]}, alg=${args[1]}, options=${args[2]}, key=${args[3]}, keyLength=${args[4]}, iv=${args[5]}, dataIn=${args[6]}, dataInLength=${args[7]}, dataOut=${args[8]}, dataOutAvailable=${args[9]}, dataOutMoved=${args[10]})`);
  this.dataOut = args[8];
  this.dataOutLength = args[9].toInt32();
}


    // log('CCCrypt op  (0加密 1解密)  =' + args[0].toInt32());
    // log('CCCrypt alg = ' + args[1].toInt32());

    // // log('CCCrypt options = ' + args[2].toInt32());
    // log('CCCrypt key = ' + hexdump(args[3] , length(16)));
    // log('CCCrypt iv = ' + hexdump(args[5]));
    // log('CCCrypt dataIn = ' + hexdump(args[6]));
    // // log('CCCrypt dataInLength = ' + args[6].toInt32());
    // // this.dataOUT = args[8];
    // log(`CCCrypt(op=${args[0]}, alg=${args[1]}, options=${args[2]}, key=${args[3]}, keyLength=${args[4]}, iv=${args[5]}, dataIn=${args[6]}, dataInLength=${args[7]}, dataOut=${args[8]}, dataOutAvailable=${args[9]}, dataOutMoved=${args[10]})`);
  },

  onLeave(log, retval, state) {

    if (this.isOn) {
      // log('result = ' + hexdump(this.dataOut));
      log('CCCrypt result = ' + hexdump(this.dataOut));
      log('CCCrypt result = ' + this.dataOut.readCString(128)); 
    }


  }
});
