/*
 * Auto-generated by Frida. Please modify to match the signature of -[MKDebugLocationConsole updateCustomText:textColor:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[MKDebugLocationConsole updateCustomText:${args[2]} textColor:${args[3]}]`);
  },

  onLeave(log, retval, state) {
  }
});
