/*
 * Auto-generated by Frida. Please modify to match the signature of -[UITableViewCountView initWithFrame:withCountString:withCount:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[UITableViewCountView initWithFrame:${args[2]} withCountString:${args[3]} withCount:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
