/*
 * Auto-generated by Frida. Please modify to match the signature of -[UITableViewCountView setCountString:withCount:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[UITableViewCountView setCountString:${args[2]} withCount:${args[3]}]`);
  },

  onLeave(log, retval, state) {
  }
});
