/*
 * Auto-generated by Frida. Please modify to match the signature of -[_NSDataFileBackedFuture initWithStoreMetadata:directory:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[_NSDataFileBackedFuture initWithStoreMetadata:${args[2]} directory:${args[3]}]`);
  },

  onLeave(log, retval, state) {
  }
});
