/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSBigMutableString _newBigSubstringWithRange:wantsMutable:zone:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSBigMutableString _newBigSubstringWithRange:${args[2]} wantsMutable:${args[3]} zone:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
