/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSBigMutableString _setData:encoding:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSBigMutableString _setData:${args[2]} encoding:${args[3]}]`);
  },

  onLeave(log, retval, state) {
  }
});
