/*
 * Auto-generated by Frida. Please modify to match the signature of -[MFData _initWithRange:from:retainingParent:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[MFData _initWithRange:${args[2]} from:${args[3]} retainingParent:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
