/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSPinyinString hash].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSPinyinString hash]`);
  },

  onLeave(log, retval, state) {
  }
});
