/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSPinyinString initWithString:syllableCount:lastSyllableIsPartial:score:replacementCount:transpositionCount:insertionCount:deletionCount:rangeCount:ranges:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSPinyinString initWithString:${args[2]} syllableCount:${args[3]} lastSyllableIsPartial:${args[4]} score:${args[5]} replacementCount:${args[6]} transpositionCount:${args[7]} insertionCount:${args[8]} deletionCount:${args[9]} rangeCount:${args[10]} ranges:${args[11]}]`);
  },

  onLeave(log, retval, state) {
  }
});
