/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSURL _br_isInSyncedLocationWithCurrentPersonaID:strictly:foundHomeDirectory:adoptionError:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSURL _br_isInSyncedLocationWithCurrentPersonaID:${args[2]} strictly:${args[3]} foundHomeDirectory:${args[4]} adoptionError:${args[5]}]`);
  },

  onLeave(log, retval, state) {
  }
});
