/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSURL _br_isInPersonaRoot:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSURL _br_isInPersonaRoot:${args[2]}]`);
  },

  onLeave(log, retval, state) {
  }
});
