/*
 * Auto-generated by Frida. Please modify to match the signature of +[NSURL _cnui_dialRequestURLWithHandle:contact:faceTime:video:ttyType:channelIdentifier:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[NSURL _cnui_dialRequestURLWithHandle:${args[2]} contact:${args[3]} faceTime:${args[4]} video:${args[5]} ttyType:${args[6]} channelIdentifier:${args[7]}]`);
  },

  onLeave(log, retval, state) {
  }
});
