/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSURL _domain:subdomain:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSURL _domain:${args[2]} subdomain:${args[3]}]`);
  },

  onLeave(log, retval, state) {
  }
});
