/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSURL _fp_scanForURLOfChildWithName:notMatchingFileID:maximumBounceNumber:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSURL _fp_scanForURLOfChildWithName:${args[2]} notMatchingFileID:${args[3]} maximumBounceNumber:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
