/*
 * Auto-generated by Frida. Please modify to match the signature of +[NSURL _QLCreateTemporaryReplacementURLForOriginalFileAtURL:withExtension:temporaryDirectoryURL:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[NSURL _QLCreateTemporaryReplacementURLForOriginalFileAtURL:${args[2]} withExtension:${args[3]} temporaryDirectoryURL:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
