/*
 * Auto-generated by Frida. Please modify to match the signature of +[NSURL _ss_copyDictionaryForQueryString:unescapedValues:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[NSURL _ss_copyDictionaryForQueryString:${args[2]} unescapedValues:${args[3]}]`);
  },

  onLeave(log, retval, state) {
  }
});
