/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSURL bookmarkDataWithOptions:includingResourceValuesForKeys:relativeToURL:error:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSURL bookmarkDataWithOptions:${args[2]} includingResourceValuesForKeys:${args[3]} relativeToURL:${args[4]} error:${args[5]}]`);
  },

  onLeave(log, retval, state) {
  }
});
