/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSURL br_preCacheBookmarkData:versionEtag:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSURL br_preCacheBookmarkData:${args[2]} versionEtag:${args[3]}]`);
  },

  onLeave(log, retval, state) {
  }
});
