/*
 * Auto-generated by Frida. Please modify to match the signature of +[NSURL brc_fileURLWithVolumeDeviceID:fileID:isDirectory:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[NSURL brc_fileURLWithVolumeDeviceID:${args[2]} fileID:${args[3]} isDirectory:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
