/*
 * Auto-generated by Frida. Please modify to match the signature of +[NSURL cls_deleteFileAtExpectedURL:containerURL:itemID:ownerName:zoneName:completion:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[NSURL cls_deleteFileAtExpectedURL:${args[2]} containerURL:${args[3]} itemID:${args[4]} ownerName:${args[5]} zoneName:${args[6]} completion:${args[7]}]`);
  },

  onLeave(log, retval, state) {
  }
});
