/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSURL fp_copyToURL:queue:precomputedItemSize:replacePlaceholder:completion:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSURL fp_copyToURL:${args[2]} queue:${args[3]} precomputedItemSize:${args[4]} replacePlaceholder:${args[5]} completion:${args[6]}]`);
  },

  onLeave(log, retval, state) {
  }
});
