/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSURL fp_existingURLOfChildWithName:notMatchingFileID:maximumBounceNumber:forceFetchingBounceNumber:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSURL fp_existingURLOfChildWithName:${args[2]} notMatchingFileID:${args[3]} maximumBounceNumber:${args[4]} forceFetchingBounceNumber:${args[5]}]`);
  },

  onLeave(log, retval, state) {
  }
});
