/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSURL fp_issueSandboxExtensionOfClass:report:error:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSURL fp_issueSandboxExtensionOfClass:${args[2]} report:${args[3]} error:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
