/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSURL fp_moveUnderFolder:withNewName:allowBounce:allowCoordination:moveHandler:completionHandler:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSURL fp_moveUnderFolder:${args[2]} withNewName:${args[3]} allowBounce:${args[4]} allowCoordination:${args[5]} moveHandler:${args[6]} completionHandler:${args[7]}]`);
  },

  onLeave(log, retval, state) {
  }
});
