/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSURL fp_moveUnderFolder:withNewName:coordinationOptions:allowBounce:allowCoordination:moveHandler:completionHandler:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSURL fp_moveUnderFolder:${args[2]} withNewName:${args[3]} coordinationOptions:${args[4]} allowBounce:${args[5]} allowCoordination:${args[6]} moveHandler:${args[7]} completionHandler:${args[8]}]`);
  },

  onLeave(log, retval, state) {
  }
});
