/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSURL fp_renameWithNewName:allowCoordination:completionHandler:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSURL fp_renameWithNewName:${args[2]} allowCoordination:${args[3]} completionHandler:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
