/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSURL fp_reparentUnderFolder:withNewName:allowCoordination:completionHandler:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSURL fp_reparentUnderFolder:${args[2]} withNewName:${args[3]} allowCoordination:${args[4]} completionHandler:${args[5]}]`);
  },

  onLeave(log, retval, state) {
  }
});
