/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSURL fp_trashUnderFolder:completionHandler:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSURL fp_trashUnderFolder:${args[2]} completionHandler:${args[3]}]`);
  },

  onLeave(log, retval, state) {
  }
});
