/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSURL getFileSystemRepresentation:maxLength:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSURL getFileSystemRepresentation:${args[2]} maxLength:${args[3]}]`);
  },

  onLeave(log, retval, state) {
  }
});
