/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSURL initByResolvingBookmarkData:options:relativeToURL:bookmarkDataIsStale:error:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSURL initByResolvingBookmarkData:${args[2]} options:${args[3]} relativeToURL:${args[4]} bookmarkDataIsStale:${args[5]} error:${args[6]}]`);
  },

  onLeave(log, retval, state) {
  }
});
