/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSURL initFileURLWithFileSystemRepresentation:isDirectory:relativeToURL:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSURL initFileURLWithFileSystemRepresentation:${args[2]} isDirectory:${args[3]} relativeToURL:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
