/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSURL initWithScheme:host:path:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSURL initWithScheme:${args[2]} host:${args[3]} path:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
