/*
 * Auto-generated by Frida. Please modify to match the signature of +[NSURL px_tempDirectoryFileURLWithSubdirectory:fileExtension:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[NSURL px_tempDirectoryFileURLWithSubdirectory:${args[2]} fileExtension:${args[3]}]`);
  },

  onLeave(log, retval, state) {
  }
});
