/*
 * Auto-generated by Frida. Please modify to match the signature of +[NSURL px_tempDirectoryFileURLWithFileName:subdirectory:fileExtension:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[NSURL px_tempDirectoryFileURLWithFileName:${args[2]} subdirectory:${args[3]} fileExtension:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
