/*
 * Auto-generated by Frida. Please modify to match the signature of +[NSURL resourceValuesForKeys:fromBookmarkData:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[NSURL resourceValuesForKeys:${args[2]} fromBookmarkData:${args[3]}]`);
  },

  onLeave(log, retval, state) {
  }
});
