/*
 * Auto-generated by Frida. Please modify to match the signature of +[NSURL triContainerURLWithPath:containerId:containerType:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[NSURL triContainerURLWithPath:${args[2]} containerId:${args[3]} containerType:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
