/*
 * Auto-generated by Frida. Please modify to match the signature of +[NSURL URLWithDisplayIdentifier:forSearchResultDomain:andIdentifier:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[NSURL URLWithDisplayIdentifier:${args[2]} forSearchResultDomain:${args[3]} andIdentifier:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
