/*
 * Auto-generated by Frida. Please modify to match the signature of +[NSURL URLWithTelephoneNumber:addressBookUID:forceAssist:suppressAssist:wasAssisted:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[NSURL URLWithTelephoneNumber:${args[2]} addressBookUID:${args[3]} forceAssist:${args[4]} suppressAssist:${args[5]} wasAssisted:${args[6]}]`);
  },

  onLeave(log, retval, state) {
  }
});
