/*
 * Auto-generated by Frida. Please modify to match the signature of +[NSURL URLWithScheme:host:port:uri:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[NSURL URLWithScheme:${args[2]} host:${args[3]} port:${args[4]} uri:${args[5]}]`);
  },

  onLeave(log, retval, state) {
  }
});
