/*
 * Auto-generated by Frida. Please modify to match the signature of -[PQLRawInjection bindWithStatement:startingAtIndex:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[PQLRawInjection bindWithStatement:${args[2]} startingAtIndex:${args[3]}]`);
  },

  onLeave(log, retval, state) {
  }
});
