/*
 * Auto-generated by Frida. Please modify to match the signature of -[UILabel _ancestorWillUpdateFocusInContext:withAnimationCoordinator:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[UILabel _ancestorWillUpdateFocusInContext:${args[2]} withAnimationCoordinator:${args[3]}]`);
  },

  onLeave(log, retval, state) {
  }
});
