/*
 * Auto-generated by Frida. Please modify to match the signature of -[UILabel _autolayoutSpacingAtEdge:forAttribute:inContainer:isGuide:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[UILabel _autolayoutSpacingAtEdge:${args[2]} forAttribute:${args[3]} inContainer:${args[4]} isGuide:${args[5]}]`);
  },

  onLeave(log, retval, state) {
  }
});
