/*
 * Auto-generated by Frida. Please modify to match the signature of -[UILabel _autolayoutSpacingAtEdge:forAttribute:nextToNeighbor:edge:attribute:multiplier:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[UILabel _autolayoutSpacingAtEdge:${args[2]} forAttribute:${args[3]} nextToNeighbor:${args[4]} edge:${args[5]} attribute:${args[6]} multiplier:${args[7]}]`);
  },

  onLeave(log, retval, state) {
  }
});
