/*
 * Auto-generated by Frida. Please modify to match the signature of -[UILabel _ensureMetricsInRect:forDrawing:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[UILabel _ensureMetricsInRect:${args[2]} forDrawing:${args[3]}]`);
  },

  onLeave(log, retval, state) {
  }
});
