/*
 * Auto-generated by Frida. Please modify to match the signature of -[UILabel _textRectForBounds:limitedToNumberOfLines:includingShadow:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[UILabel _textRectForBounds:${args[2]} limitedToNumberOfLines:${args[3]} includingShadow:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
