/*
 * Auto-generated by Frida. Please modify to match the signature of +[JKFACECoreManager reqstByHttpthod:isForceToLoad:path:service:interface:requestData:progress:resultBlock:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[JKFACECoreManager reqstByHttpthod:${args[2]} isForceToLoad:${args[3]} path:${ObjC.Object(args[4])} service:${ObjC.Object(args[5])} interface:${ObjC.Object(args[6])} requestData:${ObjC.Object(args[7])} progress:${args[8]} resultBlock:${args[9]}]`);
  },

  onLeave(log, retval, state) {

    log("JKFACECoreManager retval: " + ObjC.Object(retval));
  }
});
