/*
 * Auto-generated by Frida. Please modify to match the signature of -[WPKCrashReportFilterAppleFmt headerStringForSystemInfo:reportID:crashTime:report:wpkConfig:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[WPKCrashReportFilterAppleFmt headerStringForSystemInfo:${args[2]} reportID:${args[3]} crashTime:${args[4]} report:${args[5]} wpkConfig:${args[6]}]`);
  },

  onLeave(log, retval, state) {
  }
});
