/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSMutableData appendCBLTVType:bytes:length:error:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSMutableData appendCBLTVType:${args[2]} bytes:${args[3]} length:${args[4]} error:${args[5]}]`);
  },

  onLeave(log, retval, state) {
  }
});
