/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSMutableData appendType:length:value:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSMutableData appendType:${args[2]} length:${args[3]} value:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
