/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSMutableData replaceBytesInRange:withBytes:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSMutableData replaceBytesInRange:${args[2]} withBytes:${args[3]}]`);
  },

  onLeave(log, retval, state) {
  }
});
