/*
 * Auto-generated by Frida. Please modify to match the signature of -[AFHTTPRequestSerializer setValue:forHTTPHeaderField:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('Methods :' + Thread.backtrace(this.context,Backtracer.ACCURATE).map(DebugSymbol.fromAddress).join('\n') + '\n');
    log(`-[AFHTTPRequestSerializer setValue:${ObjC.Object(args[2])} forHTTPHeaderField:${ObjC.Object(args[3])}]`);
  },
var t = {"roomId":"4649906","doorId":"556891","openType":"2","content":{
    "roomNumber" : "0701",
    "unitNo" : "23",
    "depName" : "怡馨苑",
    "buildingNo" : "03"
  }};
  onLeave(log, retval, state) {
  }

});
