/*
 * Auto-generated by Frida. Please modify to match the signature of -[_PASLPDictionary countByEnumeratingWithState:objects:count:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[_PASLPDictionary countByEnumeratingWithState:${args[2]} objects:${args[3]} count:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
