/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSPlaceholderMutableString initWithBytesNoCopy:length:encoding:freeWhenDone:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSPlaceholderMutableString initWithBytesNoCopy:${args[2]} length:${args[3]} encoding:${args[4]} freeWhenDone:${args[5]}]`);
  },

  onLeave(log, retval, state) {
  }
});
