/*
 * Auto-generated by Frida. Please modify to match the signature of -[_PFExternalReferenceData initForExternalLocation:safeguardLocation:data:protectionLevel:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[_PFExternalReferenceData initForExternalLocation:${args[2]} safeguardLocation:${args[3]} data:${args[4]} protectionLevel:${args[5]}]`);
  },

  onLeave(log, retval, state) {
  }
});
