/*
 * Auto-generated by Frida. Please modify to match the signature of -[_PFExternalReferenceData initWithStoreBytes:length:externalLocation:safeguardLocation:protectionLevel:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[_PFExternalReferenceData initWithStoreBytes:${args[2]} length:${args[3]} externalLocation:${args[4]} safeguardLocation:${args[5]} protectionLevel:${args[6]}]`);
  },

  onLeave(log, retval, state) {
  }
});
