/*
 * Auto-generated by Frida. Please modify to match the signature of -[WebCoreSharedBufferData initWithDataSegment:position:size:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[WebCoreSharedBufferData initWithDataSegment:${args[2]} position:${args[3]} size:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
