/*
 * Auto-generated by Frida. Please modify to match the signature of X509_verify_cert.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`X509_verify_cert(ctx=${args[0]})`);
  },

  onLeave(log, retval, state) {
  }
});
