/*
 * Auto-generated by Frida. Please modify to match the signature of -[CIFilter _crashed_when_dealloc_called_setValue_nil_forKey_probably_because_the_subclass_already_released_it:className:overridesDealloc:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[CIFilter _crashed_when_dealloc_called_setValue_nil_forKey_probably_because_the_subclass_already_released_it:${args[2]} className:${args[3]} overridesDealloc:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
