/*
 * Auto-generated by Frida. Please modify to match the signature of +[DoorDuCommonTypes commonOperation:mode:algorithm:padding:iv:key:inputData:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[DoorDuCommonTypes commonOperation:${args[2]} mode:${args[3]} algorithm:${args[4]} padding:${args[5]} iv:${args[6]} key:${args[7]} inputData:${args[8]}]`);
    log('inputData =' + hexdump(args[8]));
    log('padding =' + args[5].toInt32());
  },

  onLeave(log, retval, state) {
    log('result =' + hexdump(retval));
    log('result string =' + ObjC.Object(retval));
  }
});
