/*
 * Auto-generated by Frida. Please modify to match the signature of +[DoorDuCommonTypes encryptDataAES128CFBNoPadding:iv:key:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('AES Padding = ' + args[1].toInt32());
    log('AES iv = ' + ObjC.Object(args[3]));
    log('AES key = ' + ObjC.Object(args[4]));

  },

  onLeave(log, retval, state) {

    log('result = ' + hexdump(args[4]));
  }
});
