/*
 * Auto-generated by Frida. Please modify to match the signature of +[DoorDuCommonTypes md5Crypt32WithString:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    var str = ObjC.classes.NSString;
    var newValue = str.stringWithFormat_("{\"roomId\":\"4649906\"}\r\r\r\r{\"roomId111\":\"4649906\"}\r");
    args[2] = newValue
    if (ObjC && ObjC.available) {
      log('MD5输入数据：---' + ObjC.Object(args[2]) + '---');
     // log('MD5输入dump：---' + hexdump(args[2]) + '---');
      log('Methods :' + Thread.backtrace(this.context,Backtracer.ACCURATE).map(DebugSymbol.fromAddress).join('\n') + '\n');
    } else {
      log("Objective-C runtime not available, raw arg: " + hexdump(args[2]));
    }
  },

  onLeave(log, retval, state) {
    // 处理返回值
    log( 'value = ' + ObjC.Object(retval));
  }
});