/*
 * Auto-generated by Frida. Please modify to match the signature of -[AXAttributedString attributesAtIndex:effectiveRange:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[AXAttributedString attributesAtIndex:${args[2]} effectiveRange:${args[3]}]`);
  },

  onLeave(log, retval, state) {
  }
});
