/*
 * Auto-generated by Frida. Please modify to match the signature of -[AXAttributedString attribute:atIndex:effectiveRange:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[AXAttributedString attribute:${args[2]} atIndex:${args[3]} effectiveRange:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
