/*
 * Auto-generated by Frida. Please modify to match the signature of -[AXAttributedString enumerateAttribute:inRange:options:usingBlock:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[AXAttributedString enumerateAttribute:${args[2]} inRange:${args[3]} options:${args[4]} usingBlock:${args[5]}]`);
  },

  onLeave(log, retval, state) {
  }
});
