/*
 * Auto-generated by Frida. Please modify to match the signature of -[BSUIDefaultDateLabel setStartDate:withTimeZone:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[BSUIDefaultDateLabel setStartDate:${args[2]} withTimeZone:${args[3]}]`);
  },

  onLeave(log, retval, state) {
  }
});
