/*
 * Auto-generated by Frida. Please modify to match the signature of +[LFCGTMBase64 baseDecode:length:charset:requirePadding:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[LFCGTMBase64 baseDecode:${args[2]} length:${args[3]} charset:${args[4]} requirePadding:${args[5]}]`);
  },

  onLeave(log, retval, state) {
  }
});
