/*
 * Auto-generated by Frida. Please modify to match the signature of +[CIRenderDestination _crashed_because_nonaddressable_memory_was_passed_to_initWithBitmapData:width:height:bytesPerRow:format:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[CIRenderDestination _crashed_because_nonaddressable_memory_was_passed_to_initWithBitmapData:${args[2]} width:${args[3]} height:${args[4]} bytesPerRow:${args[5]} format:${args[6]}]`);
  },

  onLeave(log, retval, state) {
  }
});
