/*
 * Auto-generated by Frida. Please modify to match the signature of -[BeiZiHTTPRequestSerializer setValue:forHTTPHeaderField:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[BeiZiHTTPRequestSerializer setValue:${args[2]} forHTTPHeaderField:${args[3]}]`);
  },

  onLeave(log, retval, state) {
  }
});
