/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSCheapMutableString setContentsNoCopy:length:freeWhenDone:isUnicode:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSCheapMutableString setContentsNoCopy:${args[2]} length:${args[3]} freeWhenDone:${args[4]} isUnicode:${args[5]}]`);
  },

  onLeave(log, retval, state) {
  }
});
