/*
 * Auto-generated by Frida. Please modify to match the signature of CFNetworkCopySystemProxySettings.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('Methods :' + Thread.backtrace(this.context,Backtracer.ACCURATE).map(DebugSymbol.fromAddress).join('\n') + '\n');
    log('CFNetworkCopySystemProxySettings()');
  },

  onLeave(log, retval, state) {
    console.log('CFNetworkCopySystemProxySettings()' + hexdump(retval));
  }
});
