/*
 * Auto-generated by Frida. Please modify to match the signature of +[PLUUIDString parseUUIDString:uuidBuffer:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[PLUUIDString parseUUIDString:${args[2]} uuidBuffer:${args[3]}]`);
  },

  onLeave(log, retval, state) {
  }
});
