/*
 * Auto-generated by Frida. Please modify to match the signature of +[CIContext _crashed_because_nonaddressable_memory_was_passed_to_render:toBitmap:rowBytes:bounds:format:colorSpace:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[CIContext _crashed_because_nonaddressable_memory_was_passed_to_render:${args[2]} toBitmap:${args[3]} rowBytes:${args[4]} bounds:${args[5]} format:${args[6]} colorSpace:${args[7]}]`);
  },

  onLeave(log, retval, state) {
  }
});
