/*
 * Auto-generated by Frida. Please modify to match the signature of -[_PFResultData writeToURL:options:error:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[_PFResultData writeToURL:${args[2]} options:${args[3]} error:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
