/*
 * Auto-generated by Frida. Please modify to match the signature of -[_PFResultData writeToFile:atomically:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[_PFResultData writeToFile:${args[2]} atomically:${args[3]}]`);
  },

  onLeave(log, retval, state) {
  }
});
