/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSString _br_nameWithAddedExtension:makeDotFile:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSString _br_nameWithAddedExtension:${args[2]} makeDotFile:${args[3]}]`);
  },

  onLeave(log, retval, state) {
  }
});
