/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSString _cn_truncateAtLength:addEllipsisIfTrunctated:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSString _cn_truncateAtLength:${args[2]} addEllipsisIfTrunctated:${args[3]}]`);
  },

  onLeave(log, retval, state) {
  }
});
