/*
 * Auto-generated by Frida. Please modify to match the signature of +[NSString _frequencyStringForComponents:forRange:forceShort:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[NSString _frequencyStringForComponents:${args[2]} forRange:${args[3]} forceShort:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
