/*
 * Auto-generated by Frida. Please modify to match the signature of +[NSString _geo_keyStringForCacheHitWithLoadReason:tileSource:tileStyle:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[NSString _geo_keyStringForCacheHitWithLoadReason:${args[2]} tileSource:${args[3]} tileStyle:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
