/*
 * Auto-generated by Frida. Please modify to match the signature of +[NSString _geo_keyStringForCacheMissWithLoadReason:missType:tileStyle:httpStatus:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[NSString _geo_keyStringForCacheMissWithLoadReason:${args[2]} missType:${args[3]} tileStyle:${args[4]} httpStatus:${args[5]}]`);
  },

  onLeave(log, retval, state) {
  }
});
