/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSString _getCString:maxLength:encoding:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSString _getCString:${args[2]} maxLength:${args[3]} encoding:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
