/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSString _getBlockStart:end:contentsEnd:forRange:stopAtLineSeparators:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSString _getBlockStart:${args[2]} end:${args[3]} contentsEnd:${args[4]} forRange:${args[5]} stopAtLineSeparators:${args[6]}]`);
  },

  onLeave(log, retval, state) {
  }
});
