/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSString _legacy_drawInRect:withFont:lineBreakMode:alignment:lineSpacing:includeEmoji:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSString _legacy_drawInRect:${args[2]} withFont:${args[3]} lineBreakMode:${args[4]} alignment:${args[5]} lineSpacing:${args[6]} includeEmoji:${args[7]}]`);
  },

  onLeave(log, retval, state) {
  }
});
