/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSString _legacy_drawAtPoint:forWidth:withFont:lineBreakMode:letterSpacing:includeEmoji:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSString _legacy_drawAtPoint:${args[2]} forWidth:${args[3]} withFont:${args[4]} lineBreakMode:${args[5]} letterSpacing:${args[6]} includeEmoji:${args[7]}]`);
  },

  onLeave(log, retval, state) {
  }
});
