/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSString _lp_highLevelDomainFromComponents:indexOfFirstHighLevelDomainComponent:indexOfFirstTopLevelDomainComponent:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSString _lp_highLevelDomainFromComponents:${args[2]} indexOfFirstHighLevelDomainComponent:${args[3]} indexOfFirstTopLevelDomainComponent:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
