/*
 * Auto-generated by Frida. Please modify to match the signature of +[NSString _mapkit_localizedDistanceStringWithMeters:abbreviated:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[NSString _mapkit_localizedDistanceStringWithMeters:${args[2]} abbreviated:${args[3]}]`);
  },

  onLeave(log, retval, state) {
  }
});
