/*
 * Auto-generated by Frida. Please modify to match the signature of +[NSString _navigation_addPrefixToInstructions:isServer:isSpoken:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[NSString _navigation_addPrefixToInstructions:${args[2]} isServer:${args[3]} isSpoken:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
