/*
 * Auto-generated by Frida. Please modify to match the signature of +[NSString _navigation_frequencyRangeLocalizedInMinutesWithMinMinutes:maxMinutes:estimate:recurring:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[NSString _navigation_frequencyRangeLocalizedInMinutesWithMinMinutes:${args[2]} maxMinutes:${args[3]} estimate:${args[4]} recurring:${args[5]}]`);
  },

  onLeave(log, retval, state) {
  }
});
