/*
 * Auto-generated by Frida. Please modify to match the signature of +[NSString _navigation_stringForServerFormattedString:abbreviatedUnits:detail:spoken:overrideVariables:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[NSString _navigation_stringForServerFormattedString:${args[2]} abbreviatedUnits:${args[3]} detail:${args[4]} spoken:${args[5]} overrideVariables:${args[6]}]`);
  },

  onLeave(log, retval, state) {
  }
});
