/*
 * Auto-generated by Frida. Please modify to match the signature of +[NSString _navigation_stringWithCountdownValue:inToken:options:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[NSString _navigation_stringWithCountdownValue:${args[2]} inToken:${args[3]} options:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
