/*
 * Auto-generated by Frida. Please modify to match the signature of +[NSString _navigation_localizedStringForDistance:context:extraDetail:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[NSString _navigation_localizedStringForDistance:${args[2]} context:${args[3]} extraDetail:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
