/*
 * Auto-generated by Frida. Please modify to match the signature of +[NSString _navigation_stringForDistance:formatter:locale:shouldScale:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[NSString _navigation_stringForDistance:${args[2]} formatter:${args[3]} locale:${args[4]} shouldScale:${args[5]}]`);
  },

  onLeave(log, retval, state) {
  }
});
