/*
 * Auto-generated by Frida. Please modify to match the signature of +[NSString _navigation_localizedStringForDistance:detail:unitFormat:locale:useMetric:useYards:shouldScale:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[NSString _navigation_localizedStringForDistance:${args[2]} detail:${args[3]} unitFormat:${args[4]} locale:${args[5]} useMetric:${args[6]} useYards:${args[7]} shouldScale:${args[8]}]`);
  },

  onLeave(log, retval, state) {
  }
});
