/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSString _rangeOfRegularExpressionPattern:options:range:locale:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSString _rangeOfRegularExpressionPattern:${args[2]} options:${args[3]} range:${args[4]} locale:${args[5]}]`);
  },

  onLeave(log, retval, state) {
  }
});
