/*
 * Auto-generated by Frida. Please modify to match the signature of +[NSString _ti_string:matchesStringIgnoringNullity:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[NSString _ti_string:${args[2]} matchesStringIgnoringNullity:${args[3]}]`);
  },

  onLeave(log, retval, state) {
  }
});
