/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSString abEscapeStringForUnichar:and:advance:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSString abEscapeStringForUnichar:${args[2]} and:${args[3]} advance:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
