/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSString addSelfToBuffer:bufferLength:withCompletedSerializationDictionary:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSString addSelfToBuffer:${args[2]} bufferLength:${args[3]} withCompletedSerializationDictionary:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
