/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSString ax_paragraphFromPosition:inDirection:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSString ax_paragraphFromPosition:${args[2]} inDirection:${args[3]}]`);
  },

  onLeave(log, retval, state) {
  }
});
