/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSString boundingRectWithSize:options:attributes:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSString boundingRectWithSize:${args[2]} options:${args[3]} attributes:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
