/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSString br_isDocumentTooLargeForUpload:maxUploadDocumentSize:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSString br_isDocumentTooLargeForUpload:${args[2]} maxUploadDocumentSize:${args[3]}]`);
  },

  onLeave(log, retval, state) {
  }
});
