/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSString br_representableHFSFileNameWithNumber:addedExtension:makeDotFile:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSString br_representableHFSFileNameWithNumber:${args[2]} addedExtension:${args[3]} makeDotFile:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
