/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSString ch_occurrencesOfCharactersInSet:maxCount:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSString ch_occurrencesOfCharactersInSet:${args[2]} maxCount:${args[3]}]`);
  },

  onLeave(log, retval, state) {
  }
});
