/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSString commonPrefixWithString:options:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSString commonPrefixWithString:${args[2]} options:${args[3]}]`);
  },

  onLeave(log, retval, state) {
  }
});
