/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSString completePathIntoString:caseSensitive:matchesIntoArray:filterTypes:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSString completePathIntoString:${args[2]} caseSensitive:${args[3]} matchesIntoArray:${args[4]} filterTypes:${args[5]}]`);
  },

  onLeave(log, retval, state) {
  }
});
