/*
 * Auto-generated by Frida. Please modify to match the signature of +[NSString deferredLocalizedIntentsStringWithFormat:fromTable:bundle:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[NSString deferredLocalizedIntentsStringWithFormat:${args[2]} fromTable:${args[3]} bundle:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
