/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSString drawAtPoint:forWidth:withFont:lineBreakMode:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSString drawAtPoint:${args[2]} forWidth:${args[3]} withFont:${args[4]} lineBreakMode:${args[5]}]`);
  },

  onLeave(log, retval, state) {
  }
});
