/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSString fp_enumerateTokensInRange:tokenizer:usingBlock:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSString fp_enumerateTokensInRange:${args[2]} tokenizer:${args[3]} usingBlock:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
