/*
 * Auto-generated by Frida. Please modify to match the signature of +[NSString fp_representableHFSFileNameWithBase:suffix:extension:makeDotFile:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[NSString fp_representableHFSFileNameWithBase:${args[2]} suffix:${args[3]} extension:${args[4]} makeDotFile:${args[5]}]`);
  },

  onLeave(log, retval, state) {
  }
});
