/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSString getBytes:maxLength:filledLength:encoding:allowLossyConversion:range:remainingRange:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSString getBytes:${args[2]} maxLength:${args[3]} filledLength:${args[4]} encoding:${args[5]} allowLossyConversion:${args[6]} range:${args[7]} remainingRange:${args[8]}]`);
  },

  onLeave(log, retval, state) {
  }
});
