/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSString getCString:maxLength:range:remainingRange:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSString getCString:${args[2]} maxLength:${args[3]} range:${args[4]} remainingRange:${args[5]}]`);
  },

  onLeave(log, retval, state) {
  }
});
