/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSString initWithValidatedFormat:validFormatSpecifiers:locale:arguments:error:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSString initWithValidatedFormat:${args[2]} validFormatSpecifiers:${args[3]} locale:${args[4]} arguments:${args[5]} error:${args[6]}]`);
  },

  onLeave(log, retval, state) {
  }
});
