/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSString initWithFormat:locale:arguments:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSString initWithFormat:${args[2]} locale:${args[3]} arguments:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
