/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSString linguisticTagsInRange:scheme:options:orthography:tokenRanges:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSString linguisticTagsInRange:${args[2]} scheme:${args[3]} options:${args[4]} orthography:${args[5]} tokenRanges:${args[6]}]`);
  },

  onLeave(log, retval, state) {
  }
});
