/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSString populateReferencesUsingBuffer:bufferLength:andDeserializationDictionary:andDataBufferDictionary:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSString populateReferencesUsingBuffer:${args[2]} bufferLength:${args[3]} andDeserializationDictionary:${args[4]} andDataBufferDictionary:${args[5]}]`);
  },

  onLeave(log, retval, state) {
  }
});
