/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSString px_stringByTruncatingToLength:addEllipsis:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSString px_stringByTruncatingToLength:${args[2]} addEllipsis:${args[3]}]`);
  },

  onLeave(log, retval, state) {
  }
});
