/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSString sg_dataEnumeratorUsingEncoding:nullTerminated:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSString sg_dataEnumeratorUsingEncoding:${args[2]} nullTerminated:${args[3]}]`);
  },

  onLeave(log, retval, state) {
  }
});
