/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSString sizeWithFont:constrainedToSize:lineBreakMode:lineSpacing:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSString sizeWithFont:${args[2]} constrainedToSize:${args[3]} lineBreakMode:${args[4]} lineSpacing:${args[5]}]`);
  },

  onLeave(log, retval, state) {
  }
});
