/*
 * Auto-generated by Frida. Please modify to match the signature of +[NSString stringEncodingForData:encodingOptions:convertedString:usedLossyConversion:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[NSString stringEncodingForData:${args[2]} encodingOptions:${args[3]} convertedString:${args[4]} usedLossyConversion:${args[5]}]`);
  },

  onLeave(log, retval, state) {
  }
});
