/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSString stringByPaddingToLength:withString:startingAtIndex:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSString stringByPaddingToLength:${args[2]} withString:${args[3]} startingAtIndex:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
