/*
 * Auto-generated by Frida. Please modify to match the signature of +[NSString stringWithValidatedFormat:validFormatSpecifiers:error:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`+[NSString stringWithValidatedFormat:${args[2]} validFormatSpecifiers:${args[3]} error:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
