/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSString triSanitizedPathComponentWithMaxLength:addHash:error:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSString triSanitizedPathComponentWithMaxLength:${args[2]} addHash:${args[3]} error:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
