/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSString vk_stringByReplacingCharactersInSet:withString:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSString vk_stringByReplacingCharactersInSet:${args[2]} withString:${args[3]}]`);
  },

  onLeave(log, retval, state) {
  }
});
