/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSString writeToURL:atomically:encoding:error:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[NSString writeToURL:${args[2]} atomically:${args[3]} encoding:${args[4]} error:${args[5]}]`);
  },

  onLeave(log, retval, state) {
  }
});
