/*
 * Auto-generated by Frida. Please modify to match the signature of +[NSDate date].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('Methods :' + Thread.backtrace(this.context,Backtracer.ACCURATE).map(DebugSymbol.fromAddress).join('\n') + '\n');

    log(`+[NSDate date]`);
  },

  onLeave(log, retval, state) {
  }
});
