/*
 * Auto-generated by Frida. Please modify to match the signature of -[UIButtonLabel _contentDidChange:fromContent:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[UIButtonLabel _contentDidChange:${args[2]} fromContent:${args[3]}]`);
  },

  onLeave(log, retval, state) {
  }
});
