/*
 * Auto-generated by Frida. Please modify to match the signature of -[ML3ProtoSyncExportSession initWithLibrary:outputStream:syncType:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[ML3ProtoSyncExportSession initWithLibrary:${args[2]} outputStream:${args[3]} syncType:${args[4]}]`);
  },

  onLeave(log, retval, state) {
  }
});
