/*
 * Auto-generated by Frida. Please modify to match the signature of -[AFHTTPSessionManager dataTaskWithHTTPMethod:URLString:parameters:headers:uploadProgress:downloadProgress:success:failure:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('Methods :' + Thread.backtrace(this.context,Backtracer.ACCURATE).map(DebugSymbol.fromAddress).join('\n') + '\n');
    // 输出当前Cached的文件夹地址
    const cachedDirectories = ObjC.classes.NSSearchPathForDirectoriesInDomains['+searchPathForDirectoriesInDomains:inDomains:'].call(ObjC.classes.NSSearchPathForDirectoriesInDomains, 9, 1, 1);
    log('当前Cached的文件夹地址: ' + cachedDirectories.toString());
    log(`-[AFHTTPSessionManager dataTaskWithHTTPMethod:${ObjC.Object(args[2])} URLString:${ObjC.Object(args[3])} parameters:${ObjC.Object(args[4])} headers:${ObjC.Object(args[5])} uploadProgress:${args[6]} downloadProgress:${args[7]} success:${args[8]} failure:${args[9]}]`);
  },

  onLeave(log, retval, state) {
  }
});
