/*
 * Auto-generated by Frida. Please modify to match the signature of -[AFHTTPSessionManager GET:parameters:headers:progress:success:failure:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log(`-[AFHTTPSessionManager GET:${args[2]} parameters:${args[3]} headers:${args[4]} progress:${args[5]} success:${args[6]} failure:${args[7]}]`);
  },

  onLeave(log, retval, state) {
  }
});
